// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7qpwGN5ceOdfXZK1L_LfZQI1pAr9R56A',
    appId: '1:918802207832:web:620876019d20b3b0c5e62d',
    messagingSenderId: '918802207832',
    projectId: 'incubateqr',
    authDomain: 'incubateqr.firebaseapp.com',
    storageBucket: 'incubateqr.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWfF5GUyK0heKwmJAKLV-fPY-UM2x5lWw',
    appId: '1:918802207832:android:360cb96bd172c130c5e62d',
    messagingSenderId: '918802207832',
    projectId: 'incubateqr',
    storageBucket: 'incubateqr.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU1i6ImZCWFvyAxhXE2V67Fe07uQv3P7w',
    appId: '1:918802207832:ios:088c79914c933c28c5e62d',
    messagingSenderId: '918802207832',
    projectId: 'incubateqr',
    storageBucket: 'incubateqr.appspot.com',
    iosClientId: '918802207832-vmsa4qhe68htqc3c51g35qjsmojr5kjl.apps.googleusercontent.com',
    iosBundleId: 'com.example.iqapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU1i6ImZCWFvyAxhXE2V67Fe07uQv3P7w',
    appId: '1:918802207832:ios:b816092351e7681bc5e62d',
    messagingSenderId: '918802207832',
    projectId: 'incubateqr',
    storageBucket: 'incubateqr.appspot.com',
    iosClientId: '918802207832-ansdm2oodlqlsisg1l0ig1lt842j016a.apps.googleusercontent.com',
    iosBundleId: 'com.example.iqapp.RunnerTests',
  );
}
