// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7qpwGN5ceOdfXZK1L_LfZQI1pAr9R56A',
    appId: '1:918802207832:web:620876019d20b3b0c5e62d',
    messagingSenderId: '918802207832',
    projectId: 'incubateqr',
    authDomain: 'incubateqr.firebaseapp.com',
    storageBucket: 'incubateqr.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWfF5GUyK0heKwmJAKLV-fPY-UM2x5lWw',
    appId: '1:918802207832:android:d0048221e98f3af4c5e62d',
    messagingSenderId: '918802207832',
    projectId: 'incubateqr',
    storageBucket: 'incubateqr.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU1i6ImZCWFvyAxhXE2V67Fe07uQv3P7w',
    appId: '1:918802207832:ios:d801064a91037caec5e62d',
    messagingSenderId: '918802207832',
    projectId: 'incubateqr',
    storageBucket: 'incubateqr.appspot.com',
    iosClientId: '918802207832-uoi0niq9790mc9bs820mdf9ttvom4dab.apps.googleusercontent.com',
    iosBundleId: 'com.example.incubateQr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU1i6ImZCWFvyAxhXE2V67Fe07uQv3P7w',
    appId: '1:918802207832:ios:94c6d5cc89408f1cc5e62d',
    messagingSenderId: '918802207832',
    projectId: 'incubateqr',
    storageBucket: 'incubateqr.appspot.com',
    iosClientId: '918802207832-g5ol1337utlvakqpdmdgdib8sq9kaake.apps.googleusercontent.com',
    iosBundleId: 'com.example.incubateQr.RunnerTests',
  );
}
